import csv

# Ordered list of names
names = [
    "Abebe Megibar Alemu",
    "Abdurahim Muzemil Hussein",
    "Abel Erduno Hakenso",
    "Abel Tesfa Awel",
    "Abenezer Solomon Tibebe",
    "Abrham Yishak Yifat",
    "Abubeker Taha",
    "Alazar Addis Gebreselassie",
    "Anansi Sime Belay",
    "Ashenafi Bizuwork Gebreyohannes",
    "Ashenafi Dejene Negash",
    "Bemenet Aschalew Wodaj",
    "Bethlehem Getachew Beyoro",
    "Bethlehem Mengist Tiruye",
    "Betel Mekasha Debele",
    "Betsinat Amare Teshome",
    "Bezawit Girma Tsegaye",
    "Biniyam Tesfu Gasaw",
    "Binyam Abrha Abay",
    "Bisrat Maru Shibeshi",
    "Blen Redwan Shifa",
    "Biruh Tesfahun Alameraw",
    "Biruk Demissie",
    "Biruk Geremew Abza",
    "Biruk Gebru Jember",
    "Dame Abera Negeri",
    "Dagemawi Bekele Negash",
    "Dagmawi Kassa Kebede",
    "Dagmawit Sisay Feleke",
    "Dibora Taye Bekele",
    "Eden Ephrem Adege",
    "Eden Zewdu Tadesse",
    "Edilawit Manaye Endeshaw",
    "Ephraim Debel Negassa",
    "Ermias Kindalem Amogne",
    "Ermiyas Tesfaye Ayalew",
    "Esub Nadew Tekletsadik",
    "Eual Girma",
    "Eyasu Getaneh Ayele",
    "Feven Issayas Mulugeta",
    "Feven Tewelde Haile",
    "Fenet Mulugeta Ejeta",
    "Finoteloza Sisay Yilma",
    "Fikreyohanes Abera Shibru",
    "Fraol Bacha Megersa",
    "Gedion Zeyede Tefera",
    "Gizachew Mohammed Jemal",
    "Hayat Abdurezak Dari",
    "Henock Tuna",
    "Henok Asaye Liyew",
    "Henok Tadesse Kersima",
    "Hermela Andargie Wondu",
    "Hibst Dereje Fekadu",
    "Hilina Zemedkun Bejiga",
    "Hintsete Hilawe Abera",
    "Hiwot Addis Abere",
    "Hunegna Demissie Bekele",
    "Ibrahim",
    "Jiru Gutema",
    "Joshua Taye Alemayehu",
    "Kaleab Shewangizaw Melese",
    "Kaletsidike Ayalew Mekonnen",
    "Kalkidan Abreham Alemu",
    "Lamesgin Desalegn Chameno",
    "Lamrot Tariku Shire",
    "Maedot Asrat Dereb",
    "Mahlet Asrat Tefera",
    "Meheret Alemu Wolde",
    "Mekdes Assefa Fetene",
    "Meklit Asrat Tefera",
    "Meron Sisay Aregay",
    "Mikreselasie Abiy Eseye",
    "Milki Legese Geda",
    "Muhammed Ebrahim",
    "Naomi Meseret Mulatu",
    "Naomi Zerfu Shiferaw",
    "Nafargi Damena Geda",
    "Nahom Teguade Kassa",
    "Nathanael Cheramlak Wolde",
    "Nathnael Merihun Mekonnen",
    "Nathan Fisseha Tsegaye",
    "Natnael Eyuel Yohannies",
    "Natnael Yohanes Abdisa",
    "Nayet Debesay",
    "Nuel Mezemir",
    "Oliyad Mulugeta Negassa",
    "Peniel Yohannes Fuge",
    "Rahel Yabebal Addis",
    "Ruth Alemfanta Aregay",
    "Ruth Ambaw Legesse",
    "Ruth Gashahun Gebreyes",
    "Samrawit Hailaeyesus Hursa",
    "Shalom Habtamu Mihrete",
    "Sitotaw Ashagre",
    "Sisay Tadewos Yale",
    "Sophonias Tamene Seifu",
    "Tadesse Agegnehu Tebabal",
    "Teshome Birhanu Cheru",
    "Tsedeke Techane Molla",
    "Tsigemariam Zewdu Tadesse",
    "Tsion Getaneh Amsalu",
    "Tsion Melese Asfaw",
    "Venusia Biruk Denmbel",
    "Welela Bekele Regassa",
    "Wendwesen Getachew Beyene",
    "Yetmgeta Ewunetu Arega",
    "Yeshak Gashaw Mekuria",
    "Yididia Abera Otiso",
    "Yohannes Alemu Amare",
    "Yohannes Worku Demissie",
    "Yosef Gebreyesus Hagos",
    "Yosef Solomon Teferra",
    "Yoseph Berhanu Nuramo",
    "Yonasan Getachew Beshah",
    "Yonatan Yishak Yifat",
    "Yonas Ayele Tola",
    "Yonas Baysasaw Kibret",
    "Yonas Tessema Achule",
    "Yonathan Desalegn Biyadglign",
    "Zeamanuel Admasu Shibru",
    "Zufan Gebrehiwot Hadgu"
]

# Save to a CSV file
with open("full a2sv.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Name"])  # Header
    for name in names:
        writer.writerow([name]) 

print("CSV file 'names.csv' created successfully!")
